name: build test deploy

on:  
  push:
    branches: [ main ]

jobs:
  build-test-deploy:
    
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
    
    - name: Restore dependencies
      run: dotnet restore src\AspnetAzureDeploy.sln
    
    - name: Build
      run: dotnet build src\AspnetAzureDeploy.sln --configuration Release --no-restore
    
    - name: Test
      run: dotnet test src\AspnetAzureDeploy.sln --no-build --verbosity normal --configuration Release