name: build test deploy

on:  
  push:
    branches: [ main ]

env:
  AZURE_WEBAPP_NAME: webapp-0902
  AZURE_WEBAPP_PACKAGE_PATH: '.'

jobs:
  build-test-deploy:
    
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
    
    - name: Restore dependencies
      run: dotnet restore src\AspnetAzureDeploy.sln
    
    - name: Build
      run: dotnet build src\AspnetAzureDeploy.sln --configuration Release --no-restore
    
    - name: Test
      run: dotnet test src\AspnetAzureDeploy.sln --no-build --verbosity normal --configuration Release

    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}